### ISSUE TITLE
Some examples in tutorial.md failed to run.

### ISSUE THREAD

**Issue by perlawk** [gilzoide/pega-texto#2]
Hi:
When I tried the examples in the tutorial.md. A lot of examples failed to run.
After compare with the examples, I found the macro F caused the segmentation fault:
    pt_expr *e = SEQ(Q(S("+-"), -1), Q(F(isdigit), 1)); // Match integer: [+-]? \d+
  // replace Q(F with Q(C fixed all the faults.
    pt_expr *e = SEQ(Q(S("+-"), -1), Q(C(isdigit), 1)); // Match integer: [+-]? \d+

please update the tutorial.md and in the reference manual.
Thanks.

**Comment by gilzoide** [comment]
Hi there,

Yeah, version 2.0 uses the `C` macro instead of `F`. I had changed the tutorial to reflect this, but hadn't commited yet.

Thank you, and sorry about that
